### ISSUE TITLE
Create New User is not working correctly

### ISSUE THREAD

**Issue by devdanlevy2** [SpoonBoards/spoonboards#7]
This also begs the question, do we want a user once logged in to be able to create a new user?  That is an option that remains from the scaffold

**Comment by devdanlevy2** [comment]
the funny thing is that when we try to create the user, it raises an error and blows up...but it is till creating the user???  When I try to resubmit it says that the email is already taken.

**Comment by LylyG** [comment]
I removed the link to create a new user on the users/show page. I fixed the bug raising the create user error. Down the road, we should revisit the idea of an admin that can pull up users and see their boards. We can build it similarly to grade_master where teachers and students had different views.
